# Use a debian image with python 3.5 (and pip3) pre-installed
image: python:3.5-stretch

variables:
  BGD: bgd --verbose

stages:
  - test
  - post

before_script:
  - python3 -m pip install --upgrade setuptools pip
  - export PATH=~/.local/bin:${PATH}
  - python3 -m pip install --user --editable ".[tests]"

.tests-template: &linux-tests
  stage: test
  variables:
    PYTEST_ADDOPTS: "--color=yes"
  script:
    - python3 setup.py test
    - mkdir -p coverage/
    - cp .coverage coverage/coverage."${CI_JOB_NAME}"
  artifacts:
    paths:
    - coverage/

.run-dummy-job-template: &dummy-job
  stage: test
  script:
    - ${BGD} server start --allow-insecure &
    - sleep 1 # Allow server to boot
    - ${BGD} bot dummy &
    - ${BGD} execute request-dummy --wait-for-completion

tests-debian-stretch:
  <<: *linux-tests

run-dummy-job-debian:
  image: buildstream/buildstream-debian
  <<: *dummy-job

build-docs:
  stage: test
  script:
    - python3 -m pip install --user --editable ".[docs]"
    - make -C docs html
    - mkdir -p documentation/
    - cp -a docs/build/html/. documentation/
  artifacts:
    paths:
    - documentation/


coverage:
  stage: post
  coverage: '/TOTAL +\d+ +\d+ +(\d+\.\d+)%/'
  script:
    - python3 -m pip install --user --editable ".[tests]"
    - mkdir report
    - cd report
    - cp ../coverage/coverage.* .
    - ls coverage.*
    - coverage combine --rcfile=../.coveragerc -a coverage.*
    - coverage report --rcfile=../.coveragerc -m
  dependencies:
  - tests-debian-stretch

# Deploy, only for merges which land on master branch.
#
pages:
  stage: post
  dependencies:
  - tests-debian-stretch
  - build-docs
  script:
  - cp -a coverage/* public/
  - cp -a documentation/* public/
  artifacts:
    paths:
    - public/
  only:
  - master
