##
# BuildGrid's Docker Compose manifest.
#
#   ¡FOR LOCAL DEVELOPMENT ONLY!
#
# Spins-up a 'local' grid instance:
#   - Controller at http://localhost:50051
#   - CAS + AC at: http://localhost:50052
#
# Basic usage:
#  - docker-compose build
#  - docker-compose up --scale bots=10
#  - docker-compose down
#  - docker volume inspect buildgrid_data
#  - docker volume rm buildgrid_data
#  - docker image rm buildgrid:local
#
version: "3.2"

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: bgd
      POSTGRES_PASSWORD: insecure
      POSTGRES_DB: bgd
    volumes:
      - type: volume
        source: db
        target: /var/lib/postgresql/data
    networks:
      - backend
    ports:
      - "5432:5432"

  storage:
    build:
      context: .
    image: buildgrid:local
    command: [
      "server", "start", "-vvv",
      "/app/config/storage.conf"]
    volumes:
      - type: volume
        source: data
        target: /var/lib/buildgrid/store
        volume:
          nocopy: true
      - type: bind
        source: ./data/config/storage.conf
        target: /app/config/storage.conf
    ports:
      - "50052:50052"
    networks:
      - backend
      - host

  cache:
    build:
      context: .
    image: buildgrid:local
    command: [
      "server", "start", "-vvv",
      "/app/config/cache.conf"]
    volumes:
      - type: bind
        source: ./data/config/cache.conf
        target: /app/config/cache.conf
    ports:
      - "50053:50053"
    networks:
      - backend
      - host

  controller:
    image: buildgrid:local
    command: [
      "server", "start", "-vvv",
      "/app/config/controller.conf"]
    volumes:
      - type: bind
        source: ./data/config/controller.conf
        target: /app/config/controller.conf
    ports:
      - "50051:50051"
    networks:
      - backend
      - host

  bots:  # To be scaled horizontaly
    image: buildgrid:local
    command: [
      "bot", "--parent=",
      "--remote=http://controller:50051",
      "--remote-cas=http://storage:50052",
      "host-tools"]
    #   "bot", "--parent=",
    #   "--remote=http://controller:50051",
    #   "--remote-cas=http://storage:50052",
    #   "buildbox",
    #   "--local-cas", "/var/lib/buildgrid/cache",
    #   "--fuse-dir", "/mnt"]
    privileged: true
    volumes:
      - type: volume
        source: cache
        target: /var/lib/buildgrid/cache
      - type: bind
        source: ./data/bin
        target: /app/tools
    depends_on:
      - controller
    networks:
      - backend

networks:
  backend:
  host:

volumes:
  cache:
  data:
  db:
